[package]
name = "redis-microsvc"
version = "0.1.0"
authors = ["bryantdeters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-redis = "0.5.1"
actix-web = "0.7.18"
env_logger = "*"
num_cpus = "1.9.0"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.84"
futures = "0.1.25"
redis-async = "0.4.4"
chrono = "0.4.6"