[package]
name = "redis-microsvc"
version = "0.1.0"
authors = ["bryantdeters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-redis = "0.5"
actix-web = "0.7"
chrono = "0.4"
env_logger = "0.6"
futures = "0.1"
guid-create = "0.1"
itertools = "0.8"
redis-async = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
